### ISSUE TITLE
Can't execute kubectl without oauth device prompt after running this

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/aks-set-context#63]
I have the following:

```
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.BETA_AZURE_CREDENTIALS }}
      - uses: azure/setup-kubectl@v2.0
      - uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ secrets.BETA_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.BETA_AKS_CLUSTER }}
      - run: kubectl -n pltfrmd set image deployments/account account=${{ secrets.BETA_ACR_SERVER }}/account:${{ github.sha }} 

```

From everything I've read, the implication is that after using aks-set-context you can then run kubectl commands. But when I run this, I get a prompt to open a web browser with a code in the action logs. I've verified all of the variables are set correctly, but no joy. Please provide documentation on how we'd use this to execute a kubectl command reliably.
