### ISSUE TITLE
BadGatewayConnection when using the action

### ISSUE THREAD

**Issue by argamanza** [Azure/aks-set-context#8]
## Expected Behavior
The action should pass successfully and the workflow should start using the K8S context i choose as its Kubernetes context.

## Actual Behavior
The actions hangs for few minutes and then fails with the message:
```
##[error]{"error":{"code":"BadGatewayConnection","message":"The network connectivity issue encountered for 'Microsoft.ContainerService'; cannot fulfill the request."}}
##[error]Node run failed with exit code 1
```

![2020-01-05_16-20](https://user-images.githubusercontent.com/9576019/71781417-58a67700-2fd7-11ea-8d07-4d753e127e5e.png)

## Steps to Reproduce the Problem

  1. Use `aks-set-context` action as follows:
```yaml
# Set the target AKS cluster
- name: Set k8s context
  uses: Azure/aks-set-context@v1
  with:
    creds: "${{ env.azure_service_principal }}"
    resource-group: abcd-qa
    cluster-name: abcd-qa-k8s
```
 2. Trigger the workflow.

## Notes
1. The same workflow worked just minutes before this issue began to occur - same workflow with exactly the same YAML and exactly the same credentials etc.
**_Nothing was changed neither in the workflow nor the environment!_**
2. I tried recreating a *service principal* using `az ad sp create-for-rbac --sdk-auth` and changed the workflow to use that, it didn't help.
